### ISSUE TITLE
This does not work with the latest version of Flarum

### ISSUE THREAD

**Issue by Blackmamba23** [spookygames/flarum-ext-auth-keycloak#11]
Having issues with the settings menu not showing up to fill in the configuration details.  Getting the below error:

> Uncaught Error: The ModalManager can only show Modals
>     at t.e.show (ModalManagerState.js:18)
>     at e.r.a.extensionSettings.spookygames-auth-keycloak (index.js:6)
>     at I.handleEvent (render.js:888)

..with flarum version - 0.1.0-beta.15
Also wondering if there is any reason this will not work with keycloak V9?

**Comment by arthurtemple** [comment]
Latest version of the plugin (`0.1.0-beta.8.1-6`) should work with Keycloak versions up to current 13.0.1.

I'll soon work on making the plugin compatible with more recent versions of Flarum.

**Comment by arthurtemple** [comment]
You might try version `0.1.0-beta.15-1`, it should work fine with Flarum 0.1.0-beta.15.

**Comment by arthurtemple** [comment]
And version `1.0-1` should be compatible with Flarum 1.0.
