### ISSUE TITLE
Regarding using flarum-ext-auth-keycloak behind proxy

### ISSUE THREAD

**Issue by LifeHackerBee** [spookygames/flarum-ext-auth-keycloak#19]
Hi,

I am wondering how I could use this extension behind a proxy? When I tried to auth, it shown me: 

Failed to get access token: cURL error 7: Failed to connect to x.x.x.x port 8443: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by arthurtemple** [comment]
Hello,

Never tried to access a Keycloak server behind a proxy.

Unfortunately, I guess it should be addressed upstream anyway: https://github.com/stevenmaguire/oauth2-keycloak.

**Comment by arthurtemple** [comment]
Closing this as I don't know how the issue could be handled in this library.
Please open an issue upstream if this is still a problem, or feel free to re-open this one if I am mistaken.
