### ISSUE TITLE
Remove existing French locales to use the French language pack

### ISSUE THREAD

**Issue by qiaeru** [spookygames/flarum-ext-auth-keycloak#20]
Hey there,

Thanks for your extension!

[Hiob](https://github.com/Hiobi) and I are the maintainer of the [French language pack for Flarum](https://github.com/flarum-lang/french). We also take care of the French translation of third party extensions like this one. We noticed that your extension already has a French translation. However, we think it is better that we take care of this translation so that all translations are standardized. We suggest that you delete the `flarum-ext-auth-keycloak/locale/fr.yml` file so that our language pack can take care of the French translation of your extension. So you can focus on the English locale and the development of your extension, our community and we take care of the French translation! 😉 

As long as the existing French locale remains, we will not be able to integrate it via Weblate into our language pack (it is a guarantee to avoid conflicts).

What do you think about that?

Best regards,

**Comment by arthurtemple** [comment]
Hello,

Thanks for the attention and kind initiative!

File was removed in latest commit: https://github.com/spookygames/flarum-ext-auth-keycloak/commit/b8126e9afb3a59392e509a08decf1af66ccd4830.

Please let me know of its integration status in your project.

Cheers!

**Comment by rob006** [comment]
French language for this extension is now available on Weblate: https://weblate.rob006.net/projects/flarum/spookygames-auth-keycloak/fr/
