### ISSUE TITLE
Flarum does not support non-English, numeric underscores as usernames

### ISSUE THREAD

**Issue by Dracowyn** [spookygames/flarum-ext-auth-keycloak#21]
Hello,
Thank you for the extension.
If a user in Keycloak has a username that is not English or uses other characters as a username, this will result in a login error. It is recommended to use random characters for the user name, use the nickname field to store the non-English user name and leave it untouched if it matches the Flarum user name rules, and set the nickname to NULL.

**Comment by arthurtemple** [comment]
Thanks a lot for the feedback. I'll take a look in the next few days.

**Comment by arthurtemple** [comment]
Should be fixed in version 1.0.0.4.

In order for this to work, the [Nicknames extension](https://github.com/flarum/nicknames) must be enabled.
