### ISSUE TITLE
Solution : "Failed to update Flarum User" when have no account

### ISSUE THREAD

**Issue by julienfollow** [spookygames/flarum-ext-auth-keycloak#22]
Hello
I'm here to explain a non explicit error.
If you use this extension and you have user who can connect with keycloak but not have account on Flarum (in database). You need to keep enable the option "Sign up".
Why ? 
Because, if you disable the sign up option, a message appear : `Failed to update Flarum User`.

This restriction is in RegisterUSerHandler class in flarum core
and the guilty line => 

![image](https://user-images.githubusercontent.com/70938205/147816183-5f266e47-4cec-4dc1-9644-1f123fa9bd38.png)

**Comment by arthurtemple** [comment]
I updated the readme, thanks!
