### ISSUE TITLE
Issue when clicking on login after filling credentials

### ISSUE THREAD

**Issue by MohitKumarTW** [spookygames/flarum-ext-auth-keycloak#26]
Hi,

Thank for developing this extension , it's really great and I am trying to use this in my project.
I am facing an error when clicking on login after filling credentials with keycloak, I just wanted to understand if I am making a mistake somewhere in config or something.

Any leads will be appreciated.

Fatal error: Uncaught Laminas\HttpHandlerRunner\Exception\EmitterException: Output has been emitted previously; cannot emit response in /Users/mohit.kumar1/Desktop/forum/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php:24 Stack trace: #0 /Users/mohit.kumar1/Desktop/forum/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitterTrait.php(40): Laminas\HttpHandlerRunner\Exception\EmitterException::forOutputSent() #1 /Users/mohit.kumar1/Desktop/forum/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitter.php(27): Laminas\HttpHandlerRunner\Emitter\SapiEmitter->assertNoPreviousOutput() #2 /Users/mohit.kumar1/Desktop/forum/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(98): Laminas\HttpHandlerRunner\Emitter\SapiEmitter->emit(Object(Laminas\Diactoros\Response\HtmlResponse)) #3 /Users/mohit.kumar1/Desktop/forum/vendor/flarum/core/src/Http/Server.php(45): Laminas\HttpHandlerRunner\RequestHandlerRunner->run() #4 /Users/mohit.kumar1/Desktop/forum/public/index.php(26): Flarum\Http\Server->listen() #5 {main} thrown in /Users/mohit.kumar1/Desktop/forum/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php on line 24

**Comment by arthurtemple** [comment]
Hello there,
Thanks for the feedback.

Not sure this is coming from this extension, is your Flarum fine _without_ the extension?
Following [this thread](https://discuss.flarum.org/d/30025-laminas-output-has-been-emitted-previously/4) it looks like the error message could happen for certain version of php.

**Comment by arthurtemple** [comment]
Closing now, feel free to re-open if the issue persists with this extension.
