### ISSUE TITLE
wrong redirect_uri using reverse proxy

### ISSUE THREAD

**Issue by der-peer** [spookygames/flarum-ext-auth-keycloak#5]
Hello,

I have Flarum set up on Apache (http), with nginx reverse proxy (https). So far working ok.
config php shows 'url' => 'https://fancyflarum.example.com'.

Keycloak is set up with https, working correctly with other clients.

When I hit the login button in Flarum, the login window opens, with Keycloak showing "invalid parameter: redirect_uri". Indeed, the redirect_uri is http.

This is the login URL created by Flarum/flarum-ext-auth-keycloak:
`https://fancykeycloak.example.com/auth/realms/fancyrealm/protocol/openid-connect/auth?state=21b0b657b8f123af382cb65cf97e5ce5&scope=name%2Cemail&response_type=code&approval_prompt=auto&redirect_uri=http%3A%2F%2Ffancyflarum.example.com%2Fauth%2Fkeycloak&client_id=fancyflarumclient`

**Comment by arthurtemple** [comment]
Hi,
Thanks for giving this library a go.

The library uses the following line
`$request->getAttribute('originalUri', $request->getUri())`
to define the redirect uri.

Maybe using Flarum URL setting would be wiser indeed.
What is your opinion on this?

**Comment by der-peer** [comment]
I also found this line 😀
But I didn't get it, where these values do come from in the end.

The value should be the one that's exposed via the reverse proxy. So maybe, if Flarum doesn't get that right on it's own, setting this manually would be sufficient.
I was wondering, why it's prefixed with http, but couldn't find the root for that

**Comment by arthurtemple** [comment]
There is probably something to see with the way your reverse proxy propagates the value through to Apache and how Flarum catches that, you're right.

Being no PHP expert myself, I'll look into what can be done to use Flarum settings instead.
Do not hesitate to keep me informed should you find a solution with nginx/apache configurations.

**Comment by arthurtemple** [comment]
A hacky solution to your problem would be, of course, to accept http as well as https in client configuration on Keycloak, then enforce redirection to https on nginx's end.

I push a bit on the configuration side because I would like to deviate as little as possible from what other oauth plugin developers have done.
And as far as I can see, they all seem to rely on getting the 'originalUri' attribute from the request.

**Comment by arthurtemple** [comment]
Please try version `0.1.0-beta.8.1-4` and tell me if this fixes your issue.

**Comment by der-peer** [comment]
This works great!
Though this solution doesn't really tell, why it happened 😉
