### ISSUE TITLE
Support disabling of "group" sync.

### ISSUE THREAD

**Issue by jcosmo** [spookygames/flarum-ext-auth-keycloak#7]
Would be nice if the keycloak sync could be configured so that it does not try to update the groups for the user as they log in.

This leaves it open to having flarum-local groups which are managed locally rather than having to maintain the groups in keycloak (or whatever auth system is backing keycloak)

**Comment by arthurtemple** [comment]
Good call, I'm thinking about sync'ing groups only when the "Role mapping" option is set, would this fit your needs?
